stages:
  - ${{ if eq(coalesce(parameters.container.deploy, gt(length(coalesce(parameters.container.csproj, '')), 0)), true) }}:
    - ${{ each server in parameters.container.servers }}:
      - stage: ${{ format('Deploy_{0}', replace(replace(replace(server.name, ' ', '_'), '-', '_'), '.', '_')) }}
        displayName: ${{ format('Deploy to {0}', server.name) }}
        condition: and(succeeded(), ${{ parameters.shouldDeploy }})
        dependsOn:
          - ${{ format('Build_{0}', parameters.build) }}
        jobs:
          - template: deploy_jobs.yml
            parameters:
              name: ${{ server.name }}
              repository: ${{ parameters.container.repository }}
              artifact: ${{ coalesce(parameters.container.artifact, parameters.container.repository )}}
              tag: ${{ coalesce(parameters.container.tag, '$(Build.BuildNumber)') }}
              latest: ${{ eq(coalesce(coalesce(server.latest, parameters.container.latest), true), true) }}
              registry: ${{ coalesce(server.registry, parameters.container.repository) }}
              username: ${{ server.username }}
              password: ${{ server.password }}
              environment: ${{ coalesce(server.environment, parameters.build) }}
  - ${{ each environment in parameters.container.environments }}:
    - stage: ${{ format('Publish_{0}', replace(replace(replace(environment.name, ' ', '_'), '-', '_'), '.', '_')) }}
      displayName: ${{ format('Publish to Container App {0} environment', environment.name) }}
      condition: and(succeeded(), ${{ parameters.shouldDeploy }})
      dependsOn:
        - ${{ format('Build_{0}', parameters.build) }}
        - ${{ each server in parameters.container.servers }}:
          - ${{ format('Deploy_{0}', replace(replace(replace(server.name, ' ', '_'), '-', '_'), '.', '_')) }}
        - ${{ each after in environment.deployAfter }}:
            - ${{ format('Publish_{0}', after) }}
      jobs:
        - template: publish_jobs.yml
          parameters:
            name: ${{ environment.name }}
            registry: ${{ environment.registry }}
            username: ${{ coalesce(environment.acrUsername, environment.registryUsername) }}
            password: ${{ coalesce(environment.acrPassword, environment.registryPassword) }}
            imageName: ${{ parameters.container.imageName }}
            tag: ${{ coalesce(parameters.container.tag, '$(Build.BuildNumber)') }}
            artifact: ${{ parameters.container.imageName }}
            environment: ${{ coalesce(environment.environment, environment.name, parameters.build) }}
            azureSubscription: ${{ coalesce(environment.azureSubscription, parameters.azureSubscription) }}
            containerAppName: ${{ coalesce(environment.containerAppName, environment.name) }}
            resourceGroup: ${{ coalesce(environment.resourceGroup, parameters.resourceGroup) }}
            image: ${{ format('{0}/{1}:{2}', environment.registry, parameters.container.imageName, coalesce(parameters.container.tag, '$(Build.BuildNumber)')) }}
            latest: ${{ eq(coalesce(coalesce(environment.latest, parameters.container.latest), true), true) }}
            