jobs:
  - deployment: ${{ format('{0}_Deploy', replace(replace(replace(parameters.name, ' ', '_'), '-', '_'), '.', '_')) }}
    displayName: ${{ parameters.name}} Deploy
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: ${{ parameters.artifact }}
              displayName: Download ${{ parameters.artifact }} artifact

            - script: |
                echo '${{ parameters.password }}' | regctl registry login "${{ parameters.name }}" -u "${{ parameters.username }}" --pass-stdin
              displayName: Login to registry

            - script: |
                regctl image import "${{ parameters.name }}/${{ parameters.registry }}:${{ parameters.tag }}" "$(Pipeline.Workspace)/${{ parameters.artifact }}/${{ parameters.repository }}.tar.gz"
              displayName: Push ${{ parameters.repository }}:${{ parameters.tag }} to registry

            - ${{ if eq(parameters.latest, true) }}:
              - script: |
                  regctl image import "${{ parameters.name }}/${{ parameters.registry }}:latest" "$(Pipeline.Workspace)/${{ parameters.artifact }}/${{ parameters.repository }}.tar.gz"
                displayName: Push ${{ parameters.repository }}:latest to registry
