jobs:
  - job: Build
    displayName: ${{ format('{0} Build', parameters.name) }}
    steps:
    - task: AzureCLI@2
      displayName: Bicep Build $(Build.Repository.Name) Arm Template
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript:  |
          [ -d $(build.artifactstagingdirectory)/modules ] || mkdir -p $(build.artifactstagingdirectory)/modules
          [ -d $(build.artifactstagingdirectory)/internal ] || mkdir -p $(build.artifactstagingdirectory)/internal
          az bicep build --file main.bicep --outfile "$(build.artifactstagingdirectory)/azuredeploy.json"

    - task: AzureCLI@2
      displayName: Validate $(Build.Repository.Name) Arm Template
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript:  |
          az deployment group validate --name "az-validate-$(Build.BuildNumber)" --resource-group "${{ parameters.resourceGroup }}" --template-file "$(build.artifactstagingdirectory)/azuredeploy.json" --parameters env="${{ parameters.env }}" suffix="${{ parameters.suffix }}" system="${{ parameters.system }}" version="$(Build.BuildNumber)" ${{ parameters.extraParameters }}

    - publish: $(build.artifactstagingdirectory)/azuredeploy.json
      displayName: 'Publish $(Build.Repository.Name) Artifact'
      artifact: $(Build.Repository.Name)

    - publish: ./modules
      condition: eq('${{ parameters.publish }}', true)
      displayName: Publish Bicep Modules Artifact
      artifact: modules

    - publish: ./internal
      condition: eq('${{ parameters.publish }}', true)
      displayName: Publish Bicep Internal Modules Artifact
      artifact: internal