jobs:
  - deployment: ${{ format('{0}_Deploy', parameters.name) }}
    displayName: ${{ format('{0} Deploy', parameters.name) }}
    environment: ${{ parameters.name }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              displayName: Download ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName) Artifact
              artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)

            - task: AzureCLI@2
              displayName: Deploy ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName) Artifact to "${{ parameters.resourceGroup }}"
              inputs:
                azureSubscription: '${{ parameters.azureSubscription }}'
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript:  |
                  az deployment group create --name "az-deployment-$(Build.BuildNumber)" --resource-group "${{ parameters.resourceGroup }}" --template-file "$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)/azuredeploy.json" --parameters env="${{ parameters.env }}" suffix="${{ parameters.suffix }}" system="${{ parameters.system }}" version="$(Build.BuildNumber)" ${{ parameters.extraParameters }}