jobs:
  - job: Publish
    displayName: ${{ format('{0} Publish', parameters.name) }}
    steps:
    - download: current
      artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)modules
      displayName: Download modules

    - download: current
      artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)internal
      displayName: Download internal modules

    - task: AzureCLI@2
      displayName: Publish Bicep modules to registry
      inputs:
        powerShellErrorActionPreference: 'continue'
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript:  |
          Write-Host "Ensuring bicep installed..."
          az config set auto-upgrade.prompt=no
          az config set auto-upgrade.all=no
          az upgrade --yes
          az bicep upgrade
          az version
          az bicep version
          [string] $version = '$(Build.BuildNumber)'
          [string] $RegistryName = '${{ parameters.acr}}'
          [string] $Path = '$(Pipeline.Workspace)'
          Move-Item -Path '$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)modules' -Destination '$(Pipeline.Workspace)/modules' -Force
          Move-Item -Path '$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)internal' -Destination '$(Pipeline.Workspace)/internal' -Force
          [System.Collections.Concurrent.ConcurrentBag[int]] $ExitCodes = [System.Collections.Concurrent.ConcurrentBag[int]]::new()
          Push-Location
          Set-Location $Path
          Write-Host "Publishing modules..."
          Get-ChildItem -Path $Path -Recurse -Include *.bicep | `
              ForEach-Object -Parallel {
                  [string] $moduleBaseName = [string]::Concat(
                                                [system.IO.Path]::GetDirectoryName((Resolve-Path -Relative $_.FullName)),
                                                '/',
                                                $_.BaseName
                                              ).Replace(
                                                '\',
                                                '/'
                                              ).TrimStart(
                                                '.',
                                                '/'
                                              ).ToLowerInvariant()
                  Write-Host "Publishing $moduleBaseName to br:$using:RegistryName.azurecr.io/bicep/modules/${moduleBaseName}:$using:version..."
                  az bicep publish --verbose --file $_.FullName --target br:$using:RegistryName.azurecr.io/bicep/modules/${moduleBaseName}:$using:version | Write-Host
                  ($using:ExitCodes).Add($LASTEXITCODE)
                  Write-Host "Published $moduleBaseName."
              }
          Pop-Location
          Write-Host "Done publishing modules."
          EXIT ($ExitCodes | Measure-Object -Sum).Sum

    - task: AzureCLI@2
      displayName: Install and Run BRI Tool
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          dotnet tool install --global BRI --version 2023.4.19.42
          bri inventory ${{ parameters.acr }}.azurecr.io " $(build.artifactstagingdirectory)"

    - task: ArchiveFiles@2
      displayName: Zip BRI generated files
      inputs:
        rootFolderOrFile: "$(build.artifactstagingdirectory)"
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: "$(build.artifactstagingdirectory)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)Docs-$(Build.BuildNumber).zip"
        replaceExistingArchive: true

    - publish: "$(build.artifactstagingdirectory)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)Docs-$(Build.BuildNumber).zip"
      displayName: 'Publish ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)Docs Zip Artifact'
      artifact: "${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)Docs"