jobs:
  - job: Start_VM_${{ parameters.env }}
    pool: 
      vmImage: ubuntu-latest
    steps:
        - task: AzureCLI@2
          displayName: Start ${{ parameters.env }} VM.
          inputs:
            azureSubscription: '${{ format(coalesce(coalesce(parameters.azureSubscriptionFormat, parameters.azureSubscriptionFormat), 'azdo-{0}-{1}-{2}-{3}'), parameters.devopsOrg, parameters.system, parameters.env, parameters.suffix, parameters.envName) }}'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az vm start --resource-group ${{ format(coalesce(coalesce(parameters.resourceGroupFormat, parameters.resourceGroupFormat), '{0}-{1}-{2}'), parameters.system, parameters.env, parameters.suffix, parameters.envName) }} --name ${{ format(coalesce(coalesce(parameters.vmNameFormat, parameters.vmNameFormat), '{0}-{1}-{2}'), parameters.system, parameters.env, parameters.suffix, parameters.envName) }} --verbose