jobs:
  - job: Build
    displayName: ${{ format('{0} Build', parameters.name) }}
    steps:
    - template: ../dotnetcommon/dotnet_sdk.yml
      parameters:
        useDotNetSDK: ${{ parameters.useDotNetSDK }}

    - template: ../dotnetcommon/dotnet_auth.yml
      parameters:
        sources: ${{ parameters.sources }}

    - template: ../dotnetcommon/dotnet_tool.yml
      parameters:
        toolRestore: true

    - task: AzureCLI@2
      displayName: Generate $(Build.Repository.Name) Settings Manifest
      env:
          KeyVaultSettings__VaultName: '${{ parameters.keyVaultName }}'
          EventHttpClientSettings__ApiUrl: '${{ parameters.eventApi.url}}'
          EventHttpClientSettings__ApiKey: '${{ parameters.eventApi.key}}'
          SubscriberSettings__Name: '${{ parameters.subsriber.name}}'
          SubscriberSettings__CallbackEvent: '${{ parameters.subsriber.callbackEvent}}'
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          dotnet wcomsign generate ./config ./artifacts --clean-output
        