parameters:
- name: name
  type: string
- name: env
  type: string
- name: system
  type: string
- name: suffix
  type: string
- name: azureSubscription
  type: string
- name: resourceGroup
  type: string
- name: keyVaultName
  type: string
- name: eventApi
  type: object
- name: subsriber
  type: string
- name: sources
  type: object
  default: ''
- name: resources
  type: object
  default: []
- name: useDotNetSDK
  type: object
  default: ''
jobs:
  - job: Build
    displayName: ${{ format('{0} Build', parameters.name) }}
    variables:
    - ${{ each resource in parameters.resources }}:
      - template: build_variables.yml
        parameters: ${{ resource }}
    steps:
    - template: ../dotnetcommon/dotnet_sdk.yml
      parameters:
        useDotNetSDK: ${{ parameters.useDotNetSDK }}

    - template: ../dotnetcommon/dotnet_auth.yml
      parameters:
        sources: ${{ parameters.sources }}

    - template: ../dotnetcommon/dotnet_tool.yml
      parameters:
        toolRestore: true

    - task: AzureCLI@2
      displayName: Generate $(Build.Repository.Name) Settings Manifest
      env:
          KeyVaultSettings__VaultName: '${{ parameters.keyVaultName }}'
          EventHttpClientSettings__ApiUrl: '${{ parameters.eventApi.url}}'
          EventHttpClientSettings__ApiKey: '${{ parameters.eventApi.key}}'
          SubscriberSettings__Name: '${{ parameters.subsriber.name}}'
          SubscriberSettings__CallbackEvent: '${{ parameters.subsriber.callbackEvent}}'
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        addSpnToEnvironment: true
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          dotnet wcomsign generate ./config ./artifacts --clean-output