stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ if eq(environment.deploy, true) }}:
      - stage: ${{ format('Deploy_{0}', environment.name) }}
        condition: ${{ parameters.shouldDeploy }}
        dependsOn:
          - ${{ each env in parameters.environments }}:
              - ${{ if eq(env.name, parameters.build) }}:
                - ${{ format('Build_{0}', env.name) }}
          - ${{ each after in environment.deployAfter }}:
            - ${{ format('Deploy_{0}', after) }}
        displayName: ${{ format('Deploy to {0}', environment.name) }}
        jobs:
          - template: deploy_jobs.yml
            parameters:
              name: ${{ environment.name }}
              azureSubscription: ${{ parameters.azureSubscription }}
              WebAppName: ${{ parameters.webAppName }}