jobs:
  - deployment: ${{ format('{0}_Deploy', parameters.name) }}
    displayName: ${{ parameters.name}} Deploy
    environment: ${{ parameters.name}}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)
              displayName: Download ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName) artifact

            - task: AzureRmWebAppDeployment@4
              displayName: Deploy to app service
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'webApp'
                WebAppName: ${{ parameters.webAppName }}
                packageForLinux: '$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)/*.zip'
