jobs:
- job: Publish
  displayName: ${{ format('{0} Build', parameters.name) }}
  steps:
  - template: ../dotnetcommon/dotnet_sdk.yml
    parameters:
      useDotNetSDK: ${{ parameters.useDotNetSDK }}

  - template: ../dotnetcommon/dotnet_auth.yml
    parameters:
      sources: ${{ parameters.sources }}

  - template: ../dotnetcommon/prebuild_common.yml
    parameters:
      preBuildScript: ${{ parameters.preBuildScript }}

  - template: ../dotnetcommon/dotnet_tests.yml
      parameters:
        skipTests: ${{ parameters.skipTests }}
        projectSrc: ${{ parameters.projectSrc }}

  - script: dotnet publish ${{ parameters.projectSrc }} --output "$(build.artifactstagingdirectory)" -p:Version=$(Build.BuildNumber) ${{ join(' ', parameters.buildParameters) }}
    displayName: Publish DotNet App

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(build.artifactstagingdirectory)"
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: "$(build.artifactstagingdirectory)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)-$(Build.BuildNumber).zip"
      replaceExistingArchive: true

  - publish: "$(build.artifactstagingdirectory)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)-$(Build.BuildNumber).zip"
    displayName: 'Publish ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName) Zip Artifact'
    artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)
