jobs:
- job: Publish
  displayName: ${{ format('{0} Build', parameters.name) }}
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK (global.json)'
    inputs:
      packageType: sdk
      useGlobalJson: true

  - template: ../dotnetcommon/dotnet_auth.yml
    parameters:
      sources: ${{ parameters.sources }}

  - template: ../dotnetcommon/prebuild_common.yml
    parameters:
      preBuildScript: ${{ parameters.preBuildScript }}

  - script: dotnet publish ${{ parameters.projectSrc }} --output "$(build.artifactstagingdirectory)" -p:Version=$(Build.BuildNumber) ${{ join(' ', parameters.buildParameters) }}
    displayName: Publish DotNet App

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(build.artifactstagingdirectory)"
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: "$(build.artifactstagingdirectory)/$(Build.Repository.Name)-$(Build.BuildNumber).zip"
      replaceExistingArchive: true

  - publish: "$(build.artifactstagingdirectory)/$(Build.Repository.Name)-$(Build.BuildNumber).zip"
    displayName: 'Publish $(Build.Repository.Name) Zip Artifact'
    artifact: $(Build.Repository.Name)
