stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ if eq(environment.name, parameters.build) }}:
      - stage: ${{ format('Build_{0}', environment.name) }}
        displayName: ${{ format('Build {0}', environment.name) }}
        dependsOn: ${{ parameters.dependsOn }}
        jobs:
          - template: publish_jobs.yml
            parameters:
              name: ${{ environment.name }}
              sources: ${{ parameters.sources }} #Needs to be accounted for in pipeline.
              buildParameters: ${{ parameters.buildParameters }}
              projectSrc: ${{ coalesce(parameters.projectSrc, 'src') }}
              preBuildScript: ${{ parameters.preBuildScript }}
