stages:
- template: publish_stages.yml
  parameters: ${{ parameters }}

- template: deploy_stages.yml
  parameters: ${{ parameters }}

- template: ../container/deploy_stages.yml
  parameters: ${{ parameters }}