jobs:
  - job: Build
    displayName: ${{ format('{0} Build', parameters.name) }}
    steps:
    - template: ../dotnetcommon/dotnet_sdk.yml
      parameters:
        useDotNetSDK: ${{ parameters.useDotNetSDK }}

    - template: ../dotnetcommon/dotnet_auth.yml
      parameters:
        sources: ${{ parameters.sources }}

    - template: ../dotnetcommon/dotnet_tool.yml
      parameters:
        toolRestore: ${{ parameters.toolRestore }}

    - template: ../dotnetcommon/prebuild_common.yml
      parameters:
        preBuildScript: ${{ parameters.preBuildScript }}

    - script: dotnet build ${{ parameters.projectSrc }} /p:Version=$(Build.BuildNumber) ${{ join(' ', parameters.buildParameters) }}
      displayName: 'DotNet Build'
      env: 
        ${{ if parameters.buildEnvironmentVariables }}:
          ${{ each envVar in parameters.buildEnvironmentVariables }}:
            ${{ envVar.key }}: ${{ envVar.value }}

    - template: ../dotnetcommon/dotnet_dpi.yml
      parameters:
        dpi: ${{ parameters.dpi }}
        azureSubscription: ${{ parameters.azureSubscription }}

    - template: ../dotnetcommon/dotnet_tests.yml
      parameters:
        skipTests: ${{ parameters.skipTests }}
        testMode: ${{ parameters.testMode }}
        projectSrc: ${{ parameters.projectSrc }}
        buildParameters: ${{ parameters.buildParameters }}

    - script: dotnet pack ${{ parameters.projectSrc }} --no-build --no-restore --output "$(build.artifactstagingdirectory)" /p:Version=$(Build.BuildNumber) ${{ join(' ', parameters.buildParameters) }}
      displayName: 'DotNet Package'
      env: 
        ${{ if parameters.buildEnvironmentVariables }}:
          ${{ each envVar in parameters.buildEnvironmentVariables }}:
            ${{ envVar.key }}: ${{ envVar.value }}

    - template: ../dotnetcommon/postbuild_common.yml
      parameters:
        postBuildScript: ${{ parameters.postBuildScript }}

    - task: PublishPipelineArtifact@1
      displayName: 'Publish ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName) Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/'
        archiveFilePatterns: '**/*.$(Build.BuildNumber).nupkg'
        artifactName: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)
