jobs:
  - deployment: ${{ format('{0}_Publish', parameters.name) }}
    displayName: ${{ parameters.name}} Publish
    environment: ${{ parameters.name}}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              displayName: Checkout $(Build.Repository.Name)

            - template: ../dotnetcommon/dotnet_sdk.yml
              parameters:
                useDotNetSDK: ${{ parameters.useDotNetSDK }}

            - template: ../dotnetcommon/dotnet_auth.yml
              parameters:
                sources: ${{ parameters.sources }}
                onlyPublish: true
                deploy: true

            - download: current
              displayName: Download ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName) Artifact
              artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)

            - ${{ if parameters.sources }}:
              - ${{ each source in parameters.sources }}:
                - ${{ if eq(source.publish, true) }}:
                  - script: dotnet nuget push --api-key "${{ coalesce(source.token, '', '$(System.AccessToken)') }}" --source "${{ source.name }}" "$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)/*.$(Build.BuildNumber).nupkg"
                    displayName: 'Publish to ${{ source.name }} Feed'