stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ if eq(environment.name, parameters.build) }}:
      - stage: ${{ format('PublishTo_{0}', environment.name) }}
        condition: ${{ parameters.shouldPush }}
        displayName: ${{ format('Publish to {0}', environment.name) }}
        jobs:
          - template: publish_jobs.yml
            parameters:
              name: ${{ environment.name }}
              sources: ${{ parameters.sources }}