jobs:
  - job: Generate_Site
    steps:
      - checkout: self
        fetchDepth: 0
        fetchTags: true
        displayName: Checkout $(Build.Repository.Name)

      - task: UseDotNet@2
        displayName: 'Use .NET SDK 6.0.x'
        inputs:
          packageType: sdk
          version: '6.0.x'

      - task: UseDotNet@2
        displayName: Use .NET Core from global.json
        inputs:
          useGlobalJson: true

      - template: ../dotnetcommon/dotnet_auth.yml
        parameters:
          sources: ${{ parameters.sources }}

      - template: ../dotnetcommon/prebuild_common.yml
        parameters:
          preBuildScript: ${{ parameters.preBuildScript }}

      - script: dotnet tool install --global Wcom.StaticSiteGenerator.Console --version 2023.4.26.2 --configfile ${{ parameters.projectRoot }}/nuget.config
        displayName: Installing Artifact Downloader.

      - script: dotnet tool install --global WCOM.Docs.Tools.BuildArtifactDownloader --version 2023.5.9.3 --configfile ${{ parameters.projectRoot }}/nuget.config
        displayName: Installing Build Artifact Downloader.

      #- script: dotnet tool restore --configfile ${{ parameters.projectRoot }}/nuget.config
        #displayName: .NET Tool Restore

      - pwsh: dotnet wcom-docs-buildartifactdownloader download '${{ parameters.projectRoot }}/input/.assemblies/*.yaml'
        env:
          WCOM_DOCS_DEVOPS_PAT: $(System.AccessToken)
          WCOM_DOCS_DEVOPS_ORG: ${{ parameters.devopsOrg }}
        displayName: Download Assembly Artifacts

      - pwsh: dotnet wcom-docs-buildartifactdownloader download '${{ parameters.projectRoot }}/input/.generated/*.yaml' --output '${{ parameters.projectRoot }}/input/generated'
        env:
          WCOM_DOCS_DEVOPS_PAT: $(System.AccessToken)
          WCOM_DOCS_DEVOPS_ORG: ${{ parameters.devopsOrg }}
        displayName: Download Generated Content Artifacts

      - ${{ each site in parameters.sites }}:
        - pwsh: |
            dotnet wcomsite -i ${{ parameters.projectRoot }}/input/theme -i ${{ parameters.projectRoot }}/input/generated -i ${{ parameters.projectRoot }}/input/${{ site.name }} -o "$(build.artifactstagingdirectory)/output/${{ site.name }}"
            [int] $Result = $LASTEXITCODE
            $Result
            exit $Result
          env:
            SiteName: ${{ site.name }}
          displayName: Build ${{ site.name }} HTML

        - script: |
            cp ${{ parameters.projectRoot }}/input/staticwebapp.config.json "$(build.artifactstagingdirectory)/output/${{ site.name }}/staticwebapp.config.json"
          displayName: Copy static web app config

        - publish: $(build.artifactstagingdirectory)/output/${{ site.name }}
          displayName: Publish ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).${{ site.name }} Static Site Artifact
          artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).${{ site.name }}