stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ if eq(environment.name, parameters.build) }}:
      - stage: ${{ format('Build_{0}', environment.name) }}
        displayName: ${{ format('Build {0}', environment.name) }}
        dependsOn:
        jobs:
          - template: build_jobs.yml
            parameters:
              name: ${{ environment.name }}
              env: ${{ environment.env }}
              sources: ${{ parameters.sources }}
              devopsOrg: ${{ parameters.devopsOrg }}
              sites: ${{ parameters.sites }}
              preBuildScript: ${{ parameters.preBuildScript }}
              artifactNamePrefix: ${{ parameters.artifactNamePrefix }}
              projectRoot: ${{ coalesce(parameters.projectRoot, '.') }}
              useDotNetSDK: ${{ parameters.useDotNetSDK }}