stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ if eq(environment.name, parameters.build) }}:
      - stage: ${{ format('Build_{0}', environment.name) }}
        displayName: ${{ format('Build {0}', environment.name) }}
        jobs:
          - template: build_jobs.yml
            parameters:
              name: ${{ environment.name }}
              env: ${{ environment.env }}
              sources: ${{ parameters.sources }}
              assembly_pipelines: ${{ parameters.assembly_pipelines }}
              devopsOrg: ${{ format('{0}-{1}', parameters.devopsOrg, coalesce(parameters.devopsOrgSuffix, 'devops')) }}
              siteName: ${{ coalesce(parameters.siteName, 'Documentation') }}
