jobs:
  - ${{ each site in parameters.sites }}:
    - deployment: ${{ format('{0}_{1}_Deploy', parameters.name, replace(site.name, '-', '_')) }}
      displayName: ${{ format('{0} {1} Deploy', parameters.name, site.name) }}
      environment: ${{ parameters.name }}
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                fetchDepth: 0
                displayName: Checkout $(Build.Repository.Name)

              - template: ../dotnetcommon/dotnet_sdk.yml
                parameters:
                  useDotNetSDK: ${{ parameters.useDotNetSDK }}

              - template: ../dotnetcommon/dotnet_auth.yml
                parameters:
                  sources: ${{  parameters.sources  }}

              - ${{ if eq(coalesce(parameters.installSwaCli, true), true) }}:
                - script: |
                    npm install -g @azure/static-web-apps-cli
                  displayName: Install SWA CLI

              - download: current
                artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).${{ site.name }}
                displayName: Download ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).${{ site.name }} artifact

              - task: AzureCLI@2
                displayName: Deploy '${{ site.name }} in ${{ parameters.name }} environment' using SWA CLI
                inputs:
                  azureSubscription: '${{ parameters.azureSubscription }}'
                  scriptType: pscore
                  scriptLocation: inlineScript
                  inlineScript: |
                    $ENV:AZURE_RESOURCE_GROUP='${{ parameters.resourceGroup }}'
                    $ENV:SWA_CLI_APP_NAME='${{ coalesce(site.webAppName, parameters.webAppName) }}'
                    $ENV:SWA_CLI_DEPLOYMENT_TOKEN=(az staticwebapp secrets list --resource-group $ENV:AZURE_RESOURCE_GROUP --name $ENV:SWA_CLI_APP_NAME --query "properties.apiKey" -o tsv)
                    swa deploy $(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).${{ site.name }} --env Production
                    [int] $Result = $LASTEXITCODE
                    $Result
                    exit $Result
