jobs:
  - job: Build
    displayName: ${{ format('{0} Build SSDT', parameters.name) }}
    steps:
    - template: ../dotnetcommon/dotnet_sdk.yml
      parameters:
        useDotNetSDK: ${{ parameters.useDotNetSDK }}

    - template: ../dotnetcommon/dotnet_auth.yml
      parameters:
        sources: ${{ parameters.sources }}

    - template: ../dotnetcommon/prebuild_common.yml
      parameters:
        preBuildScript: ${{ parameters.preBuildScript }}

    - script: dotnet pack ${{ parameters.projectSrc }} -p:OutputPath=$(Build.ArtifactStagingDirectory)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)/artifacts/Dacpac --output $(Build.ArtifactStagingDirectory)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)/artifacts/NuGet -p:Version=$(Build.BuildNumber) ${{ parameters.buildParameters }}
      displayName: 'DotNet Pack'

    - ${{ if coalesce(parameters.useDotNetSDK.useGlobalJson, true) }}:
      - publish: "${{ parameters.projectRoot }}global.json"
        displayName: Publishing global.json
        artifact: global.json

    - publish: "$(Build.ArtifactStagingDirectory)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)/artifacts/Dacpac"
      displayName: 'Publish ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName) Dacpac Artifact'
      artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac

    - publish: "$(Build.ArtifactStagingDirectory)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName)/artifacts/NuGet"
      displayName: 'Publish ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName) NuGet Artifact'
      artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).NuGet
