stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ if eq(environment.name, parameters.build) }}:
      - stage: ${{ format('Build_{0}', environment.name) }}
        displayName: ${{ format('Build {0}', environment.name) }}
        # ${{ if gt(length(convertToJson(environment.envPool)), 2) }}:
        #   pool: ${{ environment.envPool }}
        # ${{ if and(le(length(convertToJson(environment.envPool)), 2) , gt(length(convertToJson(parameters.pool)), 2)) }}:
        #   pool: ${{ parameters.pool }}
        dependsOn: ${{ parameters.dependsOn }}
        jobs:
          - template: build_jobs.yml
            parameters:
              name: ${{ environment.name }}
              env: ${{ environment.env }}
              buildParameters: ${{ parameters.buildParameters }}
              sources: ${{ parameters.sources }}
              projectSrc: ${{ coalesce(parameters.projectSrc, 'src') }}
              preBuildScript: ${{ parameters.preBuildScript }}
              artifactNamePrefix: ${{ parameters.artifactNamePrefix }}
              useDotNetSDK: ${{ parameters.useDotNetSDK }}
