stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ if eq(environment.name, parameters.build) }}:
      - stage: ${{ format('Build_{0}', environment.name) }}
        displayName: ${{ format('Build {0}', environment.name) }}
        ${{ if environment.envPool }}:
          pool: ${{ environment.envPool }}
        ${{ else }}:
          pool: ${{ parameters.pool }}
        dependsOn: ${{ parameters.dependsOn }}
        jobs:
          - template: build_jobs.yml
            parameters:
              name: ${{ environment.name }}
              env: ${{ environment.env }}
              buildParameters: ${{ parameters.buildParameters }}
              sources: ${{ parameters.sources }}
              projectRoot: ${{ parameters.projectRoot }}
              projectSrc: "${{ parameters.projectRoot }}${{ coalesce(parameters.projectSrc, 'src') }}"
              preBuildScript: ${{ parameters.preBuildScript }}
              artifactNamePrefix: ${{ parameters.artifactNamePrefix }}
              useDotNetSDK: ${{ parameters.useDotNetSDK }}
