jobs:
  - job: Build
    displayName: ${{ format('{0} Build SSDT', parameters.name) }}
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK (global.json)'
      inputs:
        packageType: sdk
        useGlobalJson: true

    #- script: dotnet build -maxcpucount:1 -p:NetCoreBuild=true -p:Version=$(Build.BuildNumber) -p:GenerateSmartDefaults=true ${{ parameters.buildParameters }} -p:OutputPath=$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name) src/
     # displayName: 'DotNet Build'

    - script: dotnet pack .\src\Data.Database.sln -p:OutputPath=$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)/artifacts/Dacpac --output $(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)/artifacts/NuGet -p:Version=$(Build.BuildNumber) ${{ parameters.buildParameters }}
      displayName: 'DotNet Pack'

    - publish: "$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)/artifacts/Dacpac"
      displayName: 'Publish $(Build.Repository.Name) Dacpac Artifact'
      artifact: $(Build.Repository.Name).Dacpac

    - publish: "$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)/artifacts/NuGet"
      displayName: 'Publish $(Build.Repository.Name) NuGet Artifact'
      artifact: $(Build.Repository.Name).NuGet