jobs:
  - deployment: ${{ format('{0}_Publish', parameters.env) }}
    displayName: ${{ parameters.env }} Publish
    environment: ${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              displayName: Checkout $(Build.Repository.Name)

            - template: ../dotnetcommon/dotnet_sdk.yml
              parameters:
                useDotNetSDK: ${{ parameters.useDotNetSDK }}

            - template: ../dotnetcommon/dotnet_auth.yml
              parameters:
                sources: ${{ parameters.sources }}
                onlyPublish: true
                deploy: true

            - download: current
              displayName: Download ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName) NuGet Artifact
              artifact: ${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).NuGet

            - ${{ if parameters.sources }}:
              - ${{ each source in parameters.sources }}:
                - ${{ if eq(source.publish, true) }}:
                  - ${{ each database in parameters.databases }}:
                    - script: dotnet nuget push --api-key "${{ coalesce(source.token, '', '$(System.AccessToken)') }}" --source "${{ source.name }}" "$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).NuGet/${{ database.name }}.$(Build.BuildNumber).nupkg"
                      displayName: 'Publish to ${{ source.name }} Feed'