stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ if eq(environment.name, parameters.build) }}:
      - stage: ${{ format('PublishTo_{0}', environment.name) }}
        condition: and(succeeded(), ${{ parameters.shouldPublish }})
        ${{ if ne(convertToJson(environment.envPool), '{}') }}:
          pool: ${{ environment.envPool }}
        ${{ if and(eq(convertToJson(environment.envPool), '{}'), ne(convertToJson(parameters.pool), '{}')) }}:
          pool: ${{ parameters.pool }}
        dependsOn:
          - ${{ each env in parameters.environments }}:
              - ${{ if eq(env.name, parameters.build) }}:
                - ${{ format('Build_{0}', env.name) }}
        displayName: ${{ format('Publish to {0}', environment.name) }}
        jobs:
          - template: publish_jobs.yml
            parameters:
              env: ${{ environment.name }}
              system: ${{ parameters.system }}
              suffix: ${{ parameters.suffix }}
              sources: ${{ parameters.sources }}
              databases: ${{ parameters.databases }}
              artifactNamePrefix: ${{ parameters.artifactNamePrefix }}
              useDotNetSDK: ${{ parameters.useDotNetSDK }}
