stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ if eq(environment.name, parameters.build) }}:
      - ${{ if eq(parameters.shouldDeploy, true) }}:
        - stage: ${{ format('PublishTo_{0}', environment.name) }}
          condition: and(succeeded(), ${{ parameters.shouldPublish }})
          displayName: ${{ format('Publish to {0}', environment.name) }}
          jobs:
            - template: publish_jobs.yml
              parameters:
                env: ${{ environment.name }}
                system: ${{ parameters.system }}
                suffix: ${{ parameters.suffix }}
                sources: ${{ parameters.sources }}
                databases: ${{ parameters.databases }}
